### ISSUE TITLE
Pandas throws error ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /opt/conda/lib/python3.10/site-packages/pandas/_libs/window/aggregations.cpython-310-x86_64-linux-gnu.so)

### ISSUE THREAD

**Issue by avkhimen** [iot-salzburg/gpu-jupyter#96] opened 2023-03-03 23:37 UTC
After the latest cschranz/gpu-jupyter:v1.4_cuda-11.6_ubuntu-20.04_python-only image update (March 3, 2023) (https://hub.docker.com/layers/cschranz/gpu-jupyter/v1.4_cuda-11.6_ubuntu-20.04_python-only/images/sha256-f452bacf69babf43397ba022df14197985a84c84f1c10631bd20370c4b9954e6?context=explore) when pandas is being installed the following error comes up:

client_container            | Traceback (most recent call last):
client_container            |   File "/home/jovyan/app/video_client_speed_sep_apis.py", line 40, in <module>
client_container            |     import pandas as pd
client_container            |   File "/opt/conda/lib/python3.10/site-packages/pandas/__init__.py", line 48, in <module>
client_container            |     from pandas.core.api import (
client_container            |   File "/opt/conda/lib/python3.10/site-packages/pandas/core/api.py", line 47, in <module>
client_container            |     from pandas.core.groupby import (
client_container            |   File "/opt/conda/lib/python3.10/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
client_container            |     from pandas.core.groupby.generic import (
client_container            |   File "/opt/conda/lib/python3.10/site-packages/pandas/core/groupby/generic.py", line 76, in <module>
client_container            |     from pandas.core.frame import DataFrame
client_container            |   File "/opt/conda/lib/python3.10/site-packages/pandas/core/frame.py", line 172, in <module>
client_container            |     from pandas.core.generic import NDFrame
client_container            |   File "/opt/conda/lib/python3.10/site-packages/pandas/core/generic.py", line 169, in <module>
client_container            |     from pandas.core.window import (
client_container            |   File "/opt/conda/lib/python3.10/site-packages/pandas/core/window/__init__.py", line 1, in <module>
client_container            |     from pandas.core.window.ewm import (
client_container            |   File "/opt/conda/lib/python3.10/site-packages/pandas/core/window/ewm.py", line 15, in <module>
client_container            |     import pandas._libs.window.aggregations as window_aggregations
client_container            | ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /opt/conda/lib/python3.10/site-packages/pandas/_libs/window/aggregations.cpython-310-x86_64-linux-gnu.so)

Please provide tag for older version if possible :)

**Comment by ChristophSchranz** [comment] 2023-03-06 13:10
Hi @avkhimen 
I'm sorry for the problem, that is very likely my fault. The tag v1.4 was overwritten and will be rebuilt today.
Please let me know if this problem still occurs with tags from today or later!

Unfortunately your link seems to be broken. Can you repost it if the error still occurs?

**Comment by ChristophSchranz** [comment] 2023-03-10 07:23
Closing as I suppose the issue is fixed, please reopen if the error still occurs.

**Closed by ChristophSchranz** 2023-03-10 07:23 UTC
