### ISSUE TITLE
unsatisfied condition: cuda >= 10.1

### ISSUE THREAD

**Issue by bbouffaut** [iot-salzburg/gpu-jupyter#24] opened 2020-08-19 12:21 UTC
Hello,

Thanks for your helpful work.

I followed all the installation instructions, and everything went well:
- Prerequisites with : `docker run --gpus all nvidia/cuda:10.1-base-ubuntu18.04 nvidia-smi` => OK
- docker image building => OK

Then, when I try to run the docker container, I get the following error:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: requirement error: unsatisfied condition: cuda>=10.1, please update your driver to a newer version, or use an earlier cuda container\\\\n\\\"\"": unknown.
ERRO[0003] error waiting for container: context canceled`

This is a bit confusing since, I was expecting your script to select the right cuda version + it works with nvidia-smi command. What shall I do to have this working on my host ? Many thanks for your help.

**The configuration of my host:**
- nvidia-390.138
- cuda9
- cuDNN7

**Comment by mathematicalmichael** [comment] 2020-08-19 16:57
I'd guess it's because of the cuda mismatches. I think the version is specified in the docker build, not auto-selected based on the version on your host.

**Comment by ChristophSchranz** [comment] 2020-08-24 14:09
Thanks for sharing so much details. Yes, IMHO @mathematicalmichael is right, if you have installed cuda9 there seem to be problems to install a driver for cuda>=10.1 on top of it. 
Have you already tried to decrease the CUDA driver version in `src/Dockerfile.header`? Please let me know if this works out for you!

You might have to adapt some lines in `src/Dockerfile.gpulibs` too, as e.g. Pytorch requires a specific cuda version:
https://github.com/iot-salzburg/gpu-jupyter/blob/1c8b32a23c1ac8d2c3d064a56a629a7b676d0462/src/Dockerfile.gpulibs#L19-L22

**Comment by ChristophSchranz** [comment] 2020-09-01 07:56
Closing the issue as the cause is clear and there were no comments anymore.

**Closed by ChristophSchranz** 2020-09-01 07:56 UTC
