### ISSUE TITLE
docker swarm GPU support

### ISSUE THREAD

**Issue by wangshun1121** [iot-salzburg/gpu-jupyter#11] opened 2020-06-04 09:29 UTC
I tried your protocol of gpu-jupyter deployment using docker swarm, and I managed to deploy Jupyter on my servers. But when deploying this way, GPU is no longer supported! 

Is there any suggestions?

**Comment by ChristophSchranz** [comment] 2020-06-04 10:33
Yes, you have to install the CUDA drivers on each node on which gpu-jupyter can run.
Have a look at this medium [article](https://medium.com/@christoph.schranz/set-up-your-own-gpu-based-jupyterlab-e0d45fcacf43).

**Comment by wangshun1121** [comment] 2020-06-05 02:20
CUDA is available on every node, and I gpus can be detected when containers were started directly using `docker run`. What I said is gpu parameters can't be accepted in `docker compose` yml file.

**Comment by ChristophSchranz** [comment] 2020-06-05 05:35
I can't reproduce this issue, as I use 
_doccker compose_ myself. Can you recognize the gpu if you access the container using _docker exec ..._ and then _sme_nvidia_ ?

**Comment by ChristophSchranz** [comment] 2020-06-08 08:27
Closing the issue as the error seems is not reproducible.

Please re-open if needed!

**Closed by ChristophSchranz** 2020-06-08 08:27 UTC
